### ISSUE TITLE
Cannot login via plugin

### ISSUE THREAD

**Issue by sdbbs** [xbmc-danish-addons/plugin.video.drnu#118]
Just noticed I cannot watch anything on DR kodi plugin.

When i try to watch something, I get this in log:

```
2025-05-07 13:51:58.482 T:19       info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 354 ms Periodsize 100 ms
2025-05-07 13:52:00.933 T:475469   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resources.lib.tvapi.ApiException'>
                                                   Error Contents: Login failed with: "{"error":"invalid_client_metadata","error_description":"grant_types can only contain 'implicit', 'authorization_code', 'refresh_token', or 'urn:ietf:params:oauth:grant-type:device_code'"}"
                                                   Traceback (most recent call last):
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/default.py", line 7, in <module>
                                                       handle = addon.DrDkTvAddon(plugin_url=sys.argv[0], plugin_handle=int(sys.argv[1]))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/addon.py", line 87, in __init__
                                                       self.api = tvapi.Api(self.cache_path, tr, get_setting)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/tvapi.py", line 168, in __init__
                                                       self.refresh_tokens()
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/tvapi.py", line 248, in refresh_tokens
                                                       self.read_tokens(pickle.load(fh))
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/tvapi.py", line 205, in read_tokens
                                                       tokens[0]['name'] = self.get_profile()['name']
                                                                           ^^^^^^^^^^^^^^^^^^
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/tvapi.py", line 383, in get_profile
                                                       headers = {'X-Authorization': 'Bearer ' + self.profile_token()}
                                                                                                 ^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/tvapi.py", line 277, in profile_token
                                                       self.refresh_tokens()
                                                     File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.drnu/resources/lib/tvapi.py", line 266, in refresh_tokens
                                                       raise ApiException(f'Login failed with: "{err}"')
                                                   resources.lib.tvapi.ApiException: Login failed with: "{"error":"invalid_client_metadata","error_description":"grant_types can only contain 'implicit', 'authorization_code', 'refresh_token', or 'urn:ietf:params:oauth:grant-type:device_code'"}"
                                                   -->End of Python script error report<--
                                                   
2025-05-07 13:52:00.970 T:475468   error <general>: GetDirectory - Error getting plugin://plugin.video.drnu/?listVideos=%2fliste%2f209529
2025-05-07 13:52:00.985 T:7       error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.drnu/?listVideos=%2fliste%2f209529) failed
```

Tried also to login again via plugin settings, same error

**Comment by sdbbs** [comment]
Thanks @TermeHansen - btw i think I fixed it:

Seeing it had something with caching, first I tried addon Settings / re-caching / re-cache all, that did not work.

Then I uninstalled the addon from Kodi, when it asked if I want to remove related settings, I said yes.

Then I installed the addon again - strangely, even though I said to remove all settings previously, it still remembered my username and password somehow, so I did not have to enter those.

Anyways, after the reinstall of the plugin, all streams work again.

**Comment by TermeHansen** [comment]
Good to hear, I'll still see if I can get into a similar state with any of my systems...

**Comment by TermeHansen** [comment]
yes they changed the login flow, I will try to fix and make a new release. Weird that it works for you @sdbbs ?!?

**Comment by TermeHansen** [comment]
What do you mean downloading?

Yes, luckily the refresh of a token is the same API function so if one has a token it works - apart from tæmylist etc...

**Comment by krogsbell** [comment]
I make a modified version of the original drnu addon.
I this version I can download programs with subtitles using FFMPEG or yt-dlp, for off-line use.
Normally downloads start high and get slower during the download, but this time it was different - starting at 41x and ended with 81x.

Well thats off topic ;-)

**Comment by TermeHansen** [comment]
ok, I have a new version fully working I believe - I will test it myself over the coming days to see if refresh of tokens etc. works.

but please feel free to test from this zip from my development branch: 
https://github.com/xbmc-danish-addons/plugin.video.drnu/archive/refs/heads/new_api_again.zip

**Comment by krogsbell** [comment]
First test - all back to normal - thank you ;-)

(comment in GitHub failed)

Regards

Hans




Den fre. 9. maj 2025 kl. 16.28 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by steyrs** [comment]
I have also tested your new version @TermeHansen on one of my Veros - haven't found any issues - yet.
Will let you know if anything comes up :)
